### PR TITLE
Feature/prepare to merge

### PR DESCRIPTION
**Pull request by kamellcuba**
@hilpold please review.

### CODE REVIEW

**Comment by kamellcuba** [comment]
@hilpold please ignore the first commit. is not related to this task.

**Comment by hilpold** [comment]
Hi Camilo, I took a brief look and have a few suggestions
1. Implement server list in configuration files instead of hardcoding in Startup.java
2. ref.js reloadServiceCaseIfNeeded is called each time an SR is opened or loaded, this can probably be avoided
3. Avoid storing configervers, host, et.c. globally a simple isConfigServer bool will do and thereby string comparison occurs only once. (Check the hook i emailed)

**Comment by kamellcuba** [comment]
@hilpold all done as requested.

please review this one as well (configuration files):

https://github.com/miamidade/mdcirm/pull/1229

**Comment by hilpold** [comment]
@kamellcuba ok, thank you. Checking...

**Comment by hilpold** [comment]
@kamellcuba modified a little bit, isConfigMode tested and pushed to branch. I'll now create a branch to deploy to test which has everything from your branch and the new WCS changes taht we need in test but should not go to production yet.

**Comment by hilpold** [comment]
@kamellcuba @fiallega the latest from prepare_to_merge open and mdcirm branches  + newWCS changes were deployed to test and the servers are up and ready for testing tomorrow.

in particular:
openCirm tempNewWcsAndPrepare_to_merge
mdcrim feature/feature/prepare_to_merge
was deployed; both servers are running on devconfig, which i like test, except for newWCS changes.

**Comment by hilpold** [comment]
Merged.

**Pull request closed without merging**
